config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'

  devise_for :users, controllers: { sessions: 'users/sessions' }
  devise_scope :user do
    post '/users/sign_as_demo' => 'users/sessions#sign_as_demo'
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  
  resources :categories
  resources :stores
  resources :repair_requests
  get 'pages/farewell', to: 'pages#farewell'
  get 'pages/sorry', to: 'pages#sorry'
  get '/404', to: 'errors#not_found'
  get '/406', to: 'errors#unacceptable'
  get '/500', to: 'errors#internal_server'
  get '/422', to: 'errors#unprocessable'

  require 'sidekiq/web'
  
  mount Sidekiq::Web => '/sidekiq'

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/repair_request.rb
class RepairRequest < ApplicationRecord
  belongs_to :store
  validates :client_email, :product_category, :product_name, :repair_description, presence: true
  after_create :asign_store
  after_update_commit :email_client

  private

  def asign_store
    AsignStoreJob.set(wait: 2.hours).perform_later(id)
  end

  def email_client
    UserMailer.with(repair_request: self).new_user_email.deliver_later
  end
end

app/controllers/repair_request_controller.rb
class RepairRequestController < ApplicationController

  def index 
    @repair_requests = RepairRequest.all
  end

  def show
  end

  def new
    @repair_request = RepairRequest.new
  end

  def create 
     @repair_request = RepairRequest.new(repair_request_params)
  end

  def edit
  end

  def update
     @repair_request = RepairRequest.update(repair_request_params)
  end

  def destroy
    @repair_request.destroy
  end

  private

  def repair_request_params
    params.require(:repair_request).permit(:client_email, :product_category, :product_name, :repair_description)
  end

  def find_repair_request
    @repair_request = RepairRequest.find(param[:id])
  end
end

app/controllers/repair_requests_controller.rb
class RepairRequestsController < ApplicationController
  before_action :find_repair_request, only: %i[show edit update destroy]
  skip_before_action :authenticate_user!, only: %i[new create]
 
  def index 
    @repair_requests = RepairRequest.all.sort
  end

  def show
  end

  def new
    @repair_request = RepairRequest.new
    @categories = Category.all.map {|cat| cat.name } 
  end

  def create 
     @repair_request = RepairRequest.new(repair_request_params)
     @repair_request.repair_status = 'Pending'

     #Getting the available stores that matches the product category
     @available_stores = Store.joins(:categories).where(categories: {name: @repair_request.product_category})
     if @available_stores.size == 0
       redirect_to pages_sorry_path
     else
       @repair_request.store_id = @available_stores.sort.first.id
       @repair_request.save
       redirect_to pages_farewell_path
     end
  end

  def edit
  end

  def update
     @repair_request.update(repair_request_params)
     redirect_to repair_request_path(@repair_request)
  end

  def destroy
    @repair_request.destroy
    redirect_to repair_request_path
  end

  private

  def repair_request_params
    params.require(:repair_request).permit(:client_email, :product_category, :product_name, :repair_description, :repair_price, :repair_status, :store_id)
  end

  def find_repair_request
    @repair_request = RepairRequest.find(params[:id])
  end
end

app/helpers/repair_request_helper.rb
module RepairRequestHelper
end

app/views/repair_requests/edit.html.erb
<div class="container mt-5 border border-secondary p-4 rounded" style="width:650px">
  <h1>Update the Repair Requests' Status</h1>

  <p> Plese update the status and price for the repair request:  <p>

  <%= simple_form_for (@repair_request), url: repair_request_path do |f| %>
  <%= f.input :repair_status, label: 'Status', collection: ["Pending" , "Aproved", "Denied"], input_html: {class: 'test'} %>
  <%= f.input :client_email, label: "Client's Email", disabled: true %>
  <%= f.input :product_name, label: "Product's name", disabled: true %>
  <%= f.input :product_category, label: "Product's category", disabled: true %>
  <%= f.input :repair_description, label: 'Repair details', disabled: true %>
  <%= f.input :repair_price, label: 'Price'%>
  <%= f.association :store, label: 'Store', label_method: :name, disabled: true %>
  <%= f.submit "Edit", class: "btn btn-success px-4", style:"width:100%;"%>
  <% end %>
</div>

<br>

<div class="container text-center mb-5">
  <%= link_to 'Back', repair_requests_path %>
</div>
</div>

app/views/repair_requests/index.html.erb
<div style="height:1000px">
  <div class="row" style="height:100%">
    <%= render 'shared/sidebar'%>
    <div class="col-10">
      <h1 class="text-center my-4">Repair Requests</h1>
      <div class="container">
      <table class="table table-striped table-hover">
          <thead>
            <tr>
              <th>N°</th>
              <th>Client</th>
              <th>Product</th>
              <th>Details</th>
              <th>Category</th>
              <th>Price</th>
              <th>Status</th>
              <th>Store Name</th>
            </tr>
          </thead>
          <tbody>
            <% @repair_requests.each do | request | %>
              <tr>
                <td><%= request.id %></td>
                <td><%= request.client_email %></td>
                <td><%= request.product_name %></td>
                <td><%= request.repair_description %></td>
                <td><%= request.product_category %></td>
                <td><%= request.repair_price %></td>
                <td><%= request.repair_status %></td>
                <td><%= request.store.name %></td>
                <td><%= link_to 'Show', request %></td>
                <td><%= link_to 'Edit', edit_repair_request_path(request) %></td>
                <td><%= link_to 'Delete', request, method: :delete, data: { confirm: 'Are you sure you want to delete?' } %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <br>
      </div>
    </div>

app/views/repair_requests/new.html.erb
<h1 class='text-center mt-5'>New Repair Request</h1>
<p class='text-center'>Please fill the following form:</p>

<div class="container mt-5 border border-secondary p-4 rounded" style="width:650px">
  <%= simple_form_for (@repair_request) do |f| %>
    <%= f.input :client_email, label: 'E-mail', placeholder: 'Enter your email' %>
    <%= f.input :product_category, label: 'Choose the product category', :collection => @categories %>
    <%= f.input :product_name, label: 'Product Name',placeholder: 'Enter the product name' %>
    <%= f.input :repair_description, label: 'Malfunction Description',placeholder: 'Please describe the problem with the product' %>
    <%= f.submit "Send", class: "btn btn-success px-4", style:"width:100%;"%>
  <% end %>
</div>

<br>

<div class="container text-center">
  <% link_to 'Back', root_path %>
</div>

app/views/repair_requests/show.html.erb
<h1 class="text-center">Repair Request N°: <%= @repair_request.id  %></h1>

<div class="container mt-5 p-4 rounded" style='width: 640px'>
  <div class="card mx-auto" style="width: 18rem;">
    <div class="card-body">
      <h5 class="card-title"><%= @repair_request.repair_status %></h5>
      <h6 class="card-subtitle mb-2 text-muted"><%= @repair_request.product_name %></h6>
      <ul class="list-group list-group-flush">
        <li class="list-group-item">Category: <%= @repair_request.product_category  %></li>
        <li class="list-group-item">Price: $<%= @repair_request.repair_price  %></li>
        <li class="list-group-item">Store: <%= @repair_request.store.name  %></li>
      </ul>
      <p class="card-text">Repair Details: <%= @repair_request.repair_description %> </p>
      <a href="#" class="card-link"><%= link_to 'Edit', edit_repair_request_path(@repair_request) %></a>
      <a href="#" class="card-link"><%= link_to 'Back', repair_requests_path %> </a>
    </div>
  </div>
</div>