config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'

  devise_for :users, controllers: { sessions: 'users/sessions' }
  devise_scope :user do
    post '/users/sign_as_demo' => 'users/sessions#sign_as_demo'
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  
  resources :categories
  resources :stores
  resources :repair_requests
  get 'pages/farewell', to: 'pages#farewell'
  get 'pages/sorry', to: 'pages#sorry'
  get '/404', to: 'errors#not_found'
  get '/406', to: 'errors#unacceptable'
  get '/500', to: 'errors#internal_server'
  get '/422', to: 'errors#unprocessable'

  require 'sidekiq/web'
  
  mount Sidekiq::Web => '/sidekiq'

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/store.rb
class Store < ApplicationRecord
  has_many :categories_stores
  has_many :categories, through: :categories_stores

  validates :name ,:address, presence: true
end

app/controllers/store_controller.rb
class StoreController < ApplicationController
  before_action :find_store, only: %i[edit show update destroy]

  def index 
    @stores = Store.all
  end

  def show
  end

  def new
    @store = Store.new
  end
 
  def create 
    @store = Store.new(store_params)
  end

  def edit
  end

  def update
    @store = Store.update(store_params)
  end

  def destroy 
    @store = Store.destroy
  end


  private

  def store_params
    params.require(:store).permit(:name, :address)
  end

  def find_store
    @store = Store.find(params[:id])
  end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :find_store, only: %i[edit show update destroy]

  def index 
    @stores = Store.all
  end

  def show
  end

  def new
    @store = Store.new
  end
 
  def create 
    @store = Store.new(store_params)
    @store.save
    redirect_to stores_path
  end

  def edit
  end

  def update
    @store.update(store_params)
    redirect_to store_path(@store)
  end

  def destroy 
    @store.destroy
    redirect_to stores_path
  end


  private

  def store_params
    params.require(:store).permit(:name, :address, :category_ids => [])
  end

  def find_store
    @store = Store.find(params[:id])
  end
end

app/helpers/store_helper.rb
module StoreHelper
end

app/views/stores/edit.html.erb
<h1 class='text-center mt-5'>Edit Store</h1>
<p class='text-center'>Please fill the following form:</p>

<div class="container mt-5 border border-secondary p-4 rounded" style="width:650px; background-color: white">
  <%= simple_form_for (@store) do |f| %>
    <%= f.input :name, label: 'Name', placeholder: 'Enter the store name: Ex. Tienda Los Molinos' %>
    <%= f.input :address, label: 'Address', placeholder: 'Please enter the store address' %>
    <%= f.association :categories,  input_html: { multiple: true }, as: :check_boxes  %>
    <%= f.submit "Submit", class: "btn btn-success px-4", style:"width:100%;"%>
  <% end %>
</div>

<br>

<div class="container text-center">
  <%= link_to 'Back', stores_path %>
</div>

app/views/stores/index.html.erb
<div style="height:1000px">
  <div class="row" style="height:100%">
  <%= render 'shared/sidebar'%>
  <div class="col-10">
    <h5 class="mt-5"> Stores </h5> <%= link_to "Add Store", new_store_path, class: "btn btn-success"%>
      <div class="d-flex mt-3" style="width:100%">
        <div class="row">
          <% @stores.each do |store| %>
            <div class="card m-2 rounded-card px-0 shadow" style="width: 18rem;">
            <%= link_to store do%>
              <div class="card-body">
                <h5 class="card-title"><%= store.name %></h5>
                <p class="card-text">Address: <%= store.address %></p>
              </div>
                <p class="text-center">
                  <%= link_to "Edit", edit_store_path(store), class:'btn btn-warning' %> 
                  <%= button_to "Delete", store, data: { turbo_confirm: "Are you sure?"}, method: :delete, class: "btn btn-danger"%>
                </p>
              </div>
            <%end%>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <div class="container text-center">
    <%= link_to 'Back', repair_requests_path %>
  </div>
</div>

app/views/stores/new.html.erb
<h1 class='text-center mt-5'>New Store</h1>
<p class='text-center'>Please fill the following form:</p>

<div class="container mt-5 border border-secondary p-4 rounded" style="width:650px; background-color: white">
  <%= simple_form_for (@store) do |f| %>
    <%= f.input :name, label: 'Name', placeholder: 'Enter the store name: Ex. Tienda Los Molinos' %>
    <%= f.input :address, label: 'Address', placeholder: 'Please enter the store address' %>
    <%= f.association :categories,  input_html: { multiple: true }, as: :check_boxes, class: :inline_boolean  %>
    <%= f.submit "Submit", class: "btn btn-success px-4", style:"width:100%;"%>
  <% end %>
</div>

<br>

<div class="container text-center">
  <%= link_to 'Back', stores_path %>
</div>

app/views/stores/show.html.erb
<div class="container-md">
  <h3 class="mt-5"> <%= @store.name %> </h3>
  <br>
  <h5> Available categories: </h5>
    <div class="d-flex mt-3" style="width:100%">
      <div class="row">
        <% @store.categories.each do |category| %>
          <div class="card m-2 rounded-card px-0 shadow" style="width: 18rem;">
            <div class="card-body">
              <h5 class="card-title"><%= category.name %></h5>
            </div>
              <p class="text-center">
              </p>
            </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
<div class="container text-center">
  <%= link_to 'Back', stores_path %>
</div>