config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'

  devise_for :users, controllers: { sessions: 'users/sessions' }
  devise_scope :user do
    post '/users/sign_as_demo' => 'users/sessions#sign_as_demo'
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  
  resources :categories
  resources :stores
  resources :repair_requests
  get 'pages/farewell', to: 'pages#farewell'
  get 'pages/sorry', to: 'pages#sorry'
  get '/404', to: 'errors#not_found'
  get '/406', to: 'errors#unacceptable'
  get '/500', to: 'errors#internal_server'
  get '/422', to: 'errors#unprocessable'

  require 'sidekiq/web'
  
  mount Sidekiq::Web => '/sidekiq'

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/categories_store.rb
class CategoriesStore < ApplicationRecord
  belongs_to :category
  belongs_to :store
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :categories_stores
    has_many :stores, through: :categories_stores
    
    validates :name, presence: true
end

app/models/repair_request.rb
class RepairRequest < ApplicationRecord
  belongs_to :store
  validates :client_email, :product_category, :product_name, :repair_description, presence: true
  after_create :asign_store
  after_update_commit :email_client

  private

  def asign_store
    AsignStoreJob.set(wait: 2.hours).perform_later(id)
  end

  def email_client
    UserMailer.with(repair_request: self).new_user_email.deliver_later
  end
end

app/models/store.rb
class Store < ApplicationRecord
  has_many :categories_stores
  has_many :categories, through: :categories_stores

  validates :name ,:address, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  protected

  def after_sign_in_path_for(resource)
    #return the path based on resource
    repair_requests_path
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    before_action :find_category, only: %i[show edit update destroy]

    def index 
        @categories = Category.all
    end

    def show
    end

    def new
        @category = Category.new
    end

    def create 
        @category = Category.new(category_params)
        @category.save
        redirect_to categories_path
    end

    def edit
    end

    def update
        @category.update(category_params)
        redirect_to category_path(@category)
    end

    def destroy
        @category.destroy
        redirect_to categories_path
    end
    

    private
    
    def category_params
        params.require(:category).permit(:name)
    end

    def find_category
        @category = Category.find(params[:id])
    end

end

app/controllers/category_controller.rb
class CategoryController < ApplicationController
    before_action :find_category, only: %i[show edit update destroy]

    def index 
        @categories = Category.all
    end

    def show
    end

    def new
        @category = Category.new
    end

    def create 
        @category = Category.new(category_params)
    end

    def edit
    end

    def update
        @category = Category.update(category_params)
    end

    def destroy
        @category.destroy
    end
    

    private
    
    def category_params
        params.require(:category).permit(:name)
    end

    def find_category
        @category = Category.find(params[:id])
    end

end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[not_found internal_server unprocessable unacceptable]
  
  def not_found
    render status: 404
  end

  def internal_server
    render status: 500
  end

  def unprocessable
    render status: 422
  end

  def unacceptable
    render status: 406
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[home farewell sorry]

  def home
  end

  def farewell
  end

  def sorry
  end
end

app/controllers/repair_request_controller.rb
class RepairRequestController < ApplicationController

  def index 
    @repair_requests = RepairRequest.all
  end

  def show
  end

  def new
    @repair_request = RepairRequest.new
  end

  def create 
     @repair_request = RepairRequest.new(repair_request_params)
  end

  def edit
  end

  def update
     @repair_request = RepairRequest.update(repair_request_params)
  end

  def destroy
    @repair_request.destroy
  end

  private

  def repair_request_params
    params.require(:repair_request).permit(:client_email, :product_category, :product_name, :repair_description)
  end

  def find_repair_request
    @repair_request = RepairRequest.find(param[:id])
  end
end

app/controllers/store_controller.rb
class StoreController < ApplicationController
  before_action :find_store, only: %i[edit show update destroy]

  def index 
    @stores = Store.all
  end

  def show
  end

  def new
    @store = Store.new
  end
 
  def create 
    @store = Store.new(store_params)
  end

  def edit
  end

  def update
    @store = Store.update(store_params)
  end

  def destroy 
    @store = Store.destroy
  end


  private

  def store_params
    params.require(:store).permit(:name, :address)
  end

  def find_store
    @store = Store.find(params[:id])
  end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :find_store, only: %i[edit show update destroy]

  def index 
    @stores = Store.all
  end

  def show
  end

  def new
    @store = Store.new
  end
 
  def create 
    @store = Store.new(store_params)
    @store.save
    redirect_to stores_path
  end

  def edit
  end

  def update
    @store.update(store_params)
    redirect_to store_path(@store)
  end

  def destroy 
    @store.destroy
    redirect_to stores_path
  end


  private

  def store_params
    params.require(:store).permit(:name, :address, :category_ids => [])
  end

  def find_store
    @store = Store.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def is_active(url)
    request.path == url ? "nav-link active" : 'nav-link'
  end
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/repair_request_helper.rb
module RepairRequestHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PcStoreSupportService</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application.bootstrap", media: 'all', "data-turbo-track": "reload" %>
  </head>

  <body class="d-flex flex-column min-vh-100">
    <%= render 'shared/flashes' %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <%= yield %>
  </body>
</html>

app/views/pages/farewell.html.erb
<h1 class='text-center'>Thank you!</h1>
<p class='text-center'>Now let's us reach you out!</p>

<div class="card mx-auto" style="width: 30rem;">
  <img src="https://images.unsplash.com/photo-1647427017067-8f33ccbae493?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D" class="card-img-top" alt="...">
  <div class="card-body">
    <p class="card-text text-center">Certified Technicians will evaluate the situation you described and send you back an answer with the next steps</p>
  </div>
</div>

<div class="container text-center">
  <%= link_to 'Back', root_path %>
</div>

app/views/pages/home.html.erb
<%= render 'shared/navbar' %>
<div class="container col-xxl-8 px-4 py-4">
    <div class="row flex-lg-row-reverse align-items-center g-5 py-5 justify-content-center">
      <div class="col-10 col-sm-8 col-lg-6">
        <img src="https://images.unsplash.com/photo-1658240527554-9cf987b4de49?q=80&w=1932&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D" class="d-block mx-lg-auto img-fluid" alt="Bootstrap Themes" width="700" height="500" loading="lazy">
      </div>
      <div class="col-lg-6">
        <h1 class="display-5 fw-bold lh-1 mb-3">TodoTecno Stores Repair Services</h1>
        <p class="lead">Having problems with your tech gadgets? Don't worry, we can help you with that! 
          Let us know what's the malfunction and we will answer right away with a quote and further instructions</p>
        <div class="d-grid gap-2 d-md-flex justify-content-center justify-content-md-start">
          <%= link_to "Request a repair", new_repair_request_path, class:"btn btn-primary btn-lg fw-bolder px-4 me-md-2" %>
        </div>
      </div>
    </div>
</div>

<br>

<div> 
  <p class="h3 text-center my-3 fw-bolder">  How can we help? </p>
<div>

<div class="row text-center">
    <div class="col-sm-4">
      <div class="card mx-auto border border-0" style="width: 18rem;">
        <%= image_tag('tool.svg', class:'card-img-top', style:'height:150px')%>
        <div class="card-body">
          <h5 class="card-title h5 fw-bold">Request a Repair</h5>
          <p class="card-text">In case of a product malfunction, you can submit a request for a proper diagnosis</p>
        </div>
      </div>
    </div>
    <div class="col-sm-4">
      <div class="card mx-auto border border-0" style="width: 18rem;">
        <%= image_tag('check-circle.svg', class:'card-img-top', style:'height:150px')%>
        <div class="card-body">
          <h5 class="card-title h5 fw-bold">Certified Technicians</h5>
          <p class="card-text">A certified technician will diagnose and repair your product</p>
        </div>
      </div>
    </div>
   
  <div class="col-sm-4">
      <div class="card mx-auto border border-0" style="width: 18rem;">
        <%= image_tag('cog.svg', class:'card-img-top', style:'height:150px')%>
        <div class="card-body">
          <h5 class="card-title h5 fw-bold">Genuine Parts</h5>
          <p class="card-text"> Your product will be repaired using genuine parts</p>
        </div>
      </div>
    </div>
</div>

<footer class="d-flex flex-wrap justify-content-center align-items-center py-3 border-top bg-dark text-center mt-auto">
  <!-- Copyright -->
  <div class="text-center p-3">
    <h6 class="text-light">© 2024 Copyright: Tiendas TodoTecno</h5>
  </div>
  <!-- Copyright -->
</footer>

app/views/pages/sorry.html.erb
<h1 class='text-center'>Oops!</h1>
<p class='text-center'>We do not cover that kind of product</p>

<div class="card mx-auto" style="width: 18rem;">
  <img src="https://images.unsplash.com/photo-1611288875785-f62fb9b044a7?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=397&q=80" class="card-img-top" alt="...">
  <div class="card-body">
    <p class="card-text text-center"> Please contact us through our social media for further information </p>
  </div>
</div>

<div class="container text-center">
  <%= link_to 'Volver', root_path %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="container">
    <header class="d-flex flex-wrap align-items-center justify-content-between py-3 mb-4 border-bottom">
      <%= link_to "TodoTecno Stores", root_path, class: "d-flex align-items-center col-md-6 mb-2 mb-md-0 text-primary fw-bolder text-decoration-none" %>
      <div class="col-md-6 text-end">
        <% if user_signed_in? %>
          <%= link_to "Log out", destroy_user_session_path, data: { turbo_method: :delete } , class: "btn btn-outline-primary me-2" %>
          <%= link_to "Admin Dashboard", repair_requests_path, class:"btn btn-success me-2 " %>
        <% else %>
          <%= button_to "Demo User", users_sign_as_demo_path, class:"btn btn-primary me-2 " %>
        <%end%>
      </div>
    </header>
</div>

app/views/shared/_sidebar.html.erb
<div class="d-flex flex-column flex-shrink-0 p-3 text-white bg-dark" style="width: 280px;">
    <%= link_to 'TodoTecno Stores', root_path, class:'fs-4 nav-link text-white mt-3 p-3' %>
    <hr>
    <ul class="nav nav-pills flex-column" aria-labelledby="dropdownUser1">
      <li class="nav-item">
        <%= link_to 'Home', root_path, class:'nav-link text-white m-1' %>
      </li>
      <li class="<%= is_active('/repair_requests') %>">
        <%= link_to 'Dashboard', repair_requests_path, class:'text-white m-1' %>
      </li>
      <li class="<%= is_active('/categories') %>">
        <%= link_to "Categories", categories_path, class:"text-white m-1" %>
      </li>
      <li class="<%= is_active('/stores') %>">
        <%= link_to "Stores", stores_path, class:"text-white m-1" %> 
      </li>
    </ul>
    <hr>
    <div class="dropdown">
      <a href="#" class="d-flex align-items-center text-white text-decoration-none dropdown-toggle" id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">
        <img src="https://github.com/mdo.png" alt="" width="32" height="32" class="rounded-circle me-2">
        <strong><%= current_user.email %></strong>
      </a>
      <ul class="dropdown-menu dropdown-menu-white text-small shadow" aria-labelledby="dropdownUser1" style="">
        <%= link_to "Log out", destroy_user_session_path, data: { turbo_method: :delete } , class: "dropdown-item me-2" %>
      </ul>
    </div>
  </div>