config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'

  devise_for :users, controllers: { sessions: 'users/sessions' }
  devise_scope :user do
    post '/users/sign_as_demo' => 'users/sessions#sign_as_demo'
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  
  resources :categories
  resources :stores
  resources :repair_requests
  get 'pages/farewell', to: 'pages#farewell'
  get 'pages/sorry', to: 'pages#sorry'
  get '/404', to: 'errors#not_found'
  get '/406', to: 'errors#unacceptable'
  get '/500', to: 'errors#internal_server'
  get '/422', to: 'errors#unprocessable'

  require 'sidekiq/web'
  
  mount Sidekiq::Web => '/sidekiq'

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :categories_stores
    has_many :stores, through: :categories_stores
    
    validates :name, presence: true
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    before_action :find_category, only: %i[show edit update destroy]

    def index 
        @categories = Category.all
    end

    def show
    end

    def new
        @category = Category.new
    end

    def create 
        @category = Category.new(category_params)
        @category.save
        redirect_to categories_path
    end

    def edit
    end

    def update
        @category.update(category_params)
        redirect_to category_path(@category)
    end

    def destroy
        @category.destroy
        redirect_to categories_path
    end
    

    private
    
    def category_params
        params.require(:category).permit(:name)
    end

    def find_category
        @category = Category.find(params[:id])
    end

end

app/controllers/category_controller.rb
class CategoryController < ApplicationController
    before_action :find_category, only: %i[show edit update destroy]

    def index 
        @categories = Category.all
    end

    def show
    end

    def new
        @category = Category.new
    end

    def create 
        @category = Category.new(category_params)
    end

    def edit
    end

    def update
        @category = Category.update(category_params)
    end

    def destroy
        @category.destroy
    end
    

    private
    
    def category_params
        params.require(:category).permit(:name)
    end

    def find_category
        @category = Category.find(params[:id])
    end

end

app/helpers/category_helper.rb
module CategoryHelper
end

app/views/categories/edit.html.erb
<h1 class='text-center mt-5'>Edit category </h1>
<p class='text-center'>Please fill the next form:</p>

<div class="container mt-5 border border-secondary p-4 rounded" style="width:650px; background-color: white">
  <%= simple_form_for (@category) do |f| %>
    <%= f.input :name, label: 'Name', placeholder: 'Enter the new category name' %>
    <%= f.submit "Submit", class: "btn btn-success px-4", style:"width:100%;"%>
  <% end %>
</div>

<br>

<div class="container text-center">
  <%= link_to 'Back', categories_path %>
</div>

app/views/categories/index.html.erb
<div style="height:1000px">
  <div class="row" style="height:100%">
  <%= render 'shared/sidebar'%>
  <div class="col-10">
    <h5 class="mt-5"> Categories </h5> <%= link_to "Add Category", new_category_path, class: "btn btn-success"%>
      <div class="d-flex mt-3" style="">
        <div class="row">
          <% @categories.each do |category| %>
            <div class="card m-2 rounded-card px-0 shadow" style="width: 18rem;">
              <%= link_to category do%>
              <div class="card-body">
                <h5 class="card-title"><%= category.name %></h5>
              </div>
              <div class="flex flex-column">
                <p> <%= link_to "Edit", edit_category_path(category) , class: 'btn btn-warning' %> </p>
                <p> <%= button_to "Delete", category, data: { turbo_confirm: "Are you sure?"}, method: :delete, class: "btn btn-danger"%> </p>
              </div>
            </div>
            <%end%>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <div class="container text-center">
    <%= link_to 'Back', repair_requests_path %>
  </div>
</div>

app/views/categories/new.html.erb
<h1 class='text-center mt-5'> New Category </h1>
<p class='text-center'>Please fill the next form:</p>

<div class="container mt-5 border border-secondary p-4 rounded" style="width:650px; background-color: white">
  <%= simple_form_for (@category) do |f| %>
    <%= f.input :name, label: 'Name', placeholder: 'Enter the new category name' %>
    <%= f.submit "Submit", class: "btn btn-success px-4", style:"width:100%;"%>
  <% end %>
</div>

<br>

<div class="container text-center">
  <%= link_to 'Back', categories_path %>
</div>

app/views/categories/show.html.erb
<div class="container-md">
  <h3 class="mt-5"> Category: <%= @category.name  %> </h3>
  <br>
  <h5> Available at: </h5>
    <div class="d-flex mt-3" style="width:100%">
      <div class="row">
        <% @category.stores.each do |store| %>
          <div class="card m-2 rounded-card px-0 shadow" style="width: 18rem;">
            <div class="card-body">
              <h5 class="card-title"><%= store.name %></h5>
            </div>
              <p class="text-center">
              </p>
            </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
<div class="container text-center">
  <%= link_to 'Back', categories_path %>
</div>